# Generated by Django 4.0.5 on 2022-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_product_current_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catogory',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
