# Generated by Django 4.0.5 on 2022-06-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_product_catogory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catogory',
        ),
    ]
